CREATE TABLE users (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(30) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password NUMBER(10) NOT NULL,
    age NUMBER(3) NOT NULL,
    role VARCHAR2(10) NOT NULL CHECK (role IN ('admin', 'user', 'landlord'))
);

CREATE TABLE payments (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    card_number VARCHAR2(19) NOT NULL,
    card_owner VARCHAR2(100) NOT NULL,
    expiration_date DATE NOT NULL,
    cvv_code NUMBER(3) NOT NULL,
    CONSTRAINT fk_payments_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE properties (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    address_id number(20),
    title VARCHAR2(250) NOT NULL,
    type VARCHAR2(50) NOT NULL CHECK (type IN ('Квартира', 'Дом', 'Комната')) ,
    description VARCHAR2(4000),
    rooms number(2),
    is_available NUMBER(1, 0) NOT NULL,
    average_rating NUMBER(3,2),
    price NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_properties_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_properties_address_id FOREIGN KEY (address_id) REFERENCES addresses(id)
);


CREATE TABLE addresses (
    id number(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    street_title VARCHAR2(50) NOT NULL, 
    street_address VARCHAR2(5) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    state VARCHAR2(50) NOT NULL,
    postal_code VARCHAR2(7) NOT NULL, 
    country VARCHAR2(50) NOT NULL, 
    apartment_number NUMBER(4)
)

CREATE TABLE amenities (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE property_amenities (
    property_id NUMBER(20),
    amenity_id NUMBER(20),
    CONSTRAINT fk_property_amenities_property_id FOREIGN KEY (property_id) REFERENCES properties(id),
    CONSTRAINT fk_property_amenities_amenity_id FOREIGN KEY (amenity_id) REFERENCES amenities(id),
    CONSTRAINT pk_property_amenities PRIMARY KEY (property_id, amenity_id)
);


CREATE TABLE photoes (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    property_id NUMBER(20) NOT NULL,
    url VARCHAR2(255) NOT NULL,
    "order" NUMBER(2) NOT NULL,
    CONSTRAINT fk_photoes_property_id FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE bookings (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    property_id NUMBER(20) NOT NULL,
    payment_id NUMBER(20) NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests NUMBER(2) NOT NULL,
    total_price NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) NOT NULL CHECK (status IN('Подтверждён','Отменён','Ожидание')),
    CONSTRAINT fk_bookings_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_bookings_property_id FOREIGN KEY (property_id) REFERENCES properties(id),
    CONSTRAINT fk_bookings_payment_id FOREIGN KEY (payment_id) REFERENCES payments(id)
);


CREATE TABLE ratings (
    id NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    property_id NUMBER(20) NOT NULL,
    rating NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR2(1500), 
    UNIQUE (user_id, property_id),
    CONSTRAINT fk_ratings_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ratings_property_id FOREIGN KEY (property_id) REFERENCES properties(id)
);

CREATE TABLE ratings (
    id NUMBER(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(20) NOT NULL,
    property_id NUMBER(20) NOT NULL,
    rating NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR2(1500), 
    UNIQUE (user_id, property_id),
    CONSTRAINT fk_ratings_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_ratings_property_id FOREIGN KEY (property_id) REFERENCES properties(id)
);
--========================================================
DROP TABLE bookings;
DROP TABLE photoes;
DROP TABLE property_amenities;
DROP TABLE amenities;
DROP TABLE addresses;
DROP TABLE properties;
DROP TABLE payments;
DROP TABLE users;
DROP TABLE ratings
--========================================================
INSERT INTO users (first_name, last_name, email, password, age, role)
VALUES ('John', 'syna', 'john.syna@example.com', '12345', 30, 'user');



