CREATE TABLESPACE my_tablespace
DATAFILE 'my_tablespace.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M;

CREATE ROLE my_role;
GRANT CREATE SESSION, CREATE TABLE TO my_role;

CREATE PROFILE my_profile
LIMIT
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LOCK_TIME 1
  PASSWORD_LIFE_TIME 90
  PASSWORD_REUSE_TIME 30
  PASSWORD_REUSE_MAX 10;
  
CREATE USER U1_BPI_PDB IDENTIFIED BY 1111
DEFAULT TABLESPACE my_tablespace
QUOTA UNLIMITED ON my_tablespace
PROFILE my_profile;


GRANT my_role TO U1_BPI_PDB;
DROP USER U1_BPI_PDB CASCADE;

alter database open