alter session set "_oracle_script"=true;
CREATE PROFILE C##my_profile
LIMIT
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LOCK_TIME 10
  PASSWORD_LIFE_TIME 90
  PASSWORD_REUSE_TIME 30
  PASSWORD_REUSE_MAX 10;
  
DROP PROFILE C##my_profile CASCADE


CREATE TABLESPACE C##tablespace
DATAFILE 'C##tablespace.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 10M;

drop tablespace C##tablespace including CONTENTS and DATAFILES;

SELECT * from dba_pdbs

CREATE USER C##BPI IDENTIFIED BY 1111
default tablespace C##tablespace
PROFILE C##my_profile;
DROP USER C##BPI CASCADE
CREATE USER C##IPB2 IDENTIFIED BY 1111;
CREATE USER C##BPI IDENTIFIED BY 1111;


create role C##role
GRANT CREATE SESSION TO C##role
GRANT CREATE SESSION TO C##IPB2
GRANT CREATE SESSION TO C##BPI
GRANT CREATE SESSION TO C##BPI CONTAINER=all;
GRANT CONNECT TO C##BPI CONTAINER=ALL;
GRANT CREATE SESSION TO C##IPB2 CONTAINER=all;
GRANT CREATE sequence to C##IPB2; 
GRANT CREATE TABLE TO C##IPB2;
GRANT CREATE CLUSTER TO C##IPB2;
GRANT CREATE SYNONYM TO C##IPB2;
GRANT CREATE PUBLIC SYNONYM TO C##IPB2;
GRANT CREATE MATERIALIZED VIEW TO C##IPB2;


GRANT CREATE SEQUENCE TO c##ipb2;
GRANT CREATE TABLE TO c##ipb2;
GRANT CREATE CLUSTER TO c##ipb2;
GRANT CREATE SYNONYM TO c##ipb2;
GRANT CREATE PUBLIC SYNONYM TO c##ipb2;
GRANT CREATE MATERIALIZED VIEW TO c##ipb2;
GRANT CREATE VIEW TO c##ipb2;
GRANT SYSDBA TO C##IPB2

ALTER USER C##IPB2 QUOTA 100M on USERS

SELECT * FROM DBA_USERS
SELECT NAME, PDB FROM v$services