CREATE TABLE TEST_TABLE(
ID NUMBER(10),
NAME VARCHAR2(20)
)


INSERT INTO TEST_TABLE (ID, NAME) VALUES (1, 'Alice');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (2, 'Bob');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (3, 'Charlie');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (4, 'Diana');
INSERT INTO TEST_TABLE (ID, NAME) VALUES (5, 'Edward');

drop table TEST_TABLE1;

CREATE DATABASE LINK anotherdb 
   CONNECT TO system
   IDENTIFIED BY QZ386547qz
   USING 'LAB9';
   
DROP DATABASE LINK anotherdb
   SELECT * FROM TEST_TABLE1@anotherdb;

INSERT INTO TEST_TABLE1@anotherdb (ID, NAME) VALUES (8648, 'Pavel');

commit;